services:
  postgres:
    image: postgres:latest
    container_name: postgres_l_chat
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=l_chat_dev
    ports:
      - "5431:5432"
    restart: unless-stopped